server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/auth}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}