server:
  port: 8086

spring:
  application:
    name: notification-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

kafka:
  topics:
    enrollment-created: enrollment.created
    course-completed: course.completed
    quiz-submitted: quiz.submitted