server:
  port: 8084

spring:
  application:
    name: ai-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/nexamed}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ai_service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

openai:
  api:
    key: ${OPENAI_API_KEY}
    model: gpt-4o-mini
    max-tokens: 2000
    temperature: 0.7